name: thumbolympics
description: "Compete in the ultimate thumb Olympics! Track your scroll distance and compare it to real-world landmarks. Turn doom scrolling into a playful competition!"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0-132.0.dev

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.3.0
  flutter_local_notifications: ^19.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
